"""Second Migration

Revision ID: ac5274e661e0
Revises: 7aab8c423e40
Create Date: 2026-05-21 14:48:37.358992

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ac5274e661e0'
down_revision = '7aab8c423e40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('manufacturing_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('manufacturer',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('categoria_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.alter_column('categoria_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('manufacturer',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('manufacturing_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('categoria', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
